AWSTemplateFormatVersion: '2010-09-09'
Description: Create Security Groups for EC2 Instances

Parameters:
  VPCId:
    Type: String
    Description: VPC Id

Resources:
  PublicEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from specific IP
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 42.112.228.59/32
          # CidrIP: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: PublicEC2SecurityGroup

  PrivateEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from Public EC2
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref PublicEC2SecurityGroup
      Tags:
        - Key: Name
          Value: PrivateEC2SecurityGroup

Outputs:
  PublicSecurityGroupId:
    Description: The Public EC2 Security Group Id
    Value: !Ref PublicEC2SecurityGroup

  PrivateSecurityGroupId:
    Description: The Private EC2 Security Group Id
    Value: !Ref PrivateEC2SecurityGroup
  
