AWSTemplateFormatVersion: '2010-09-09'
Description: Create Public and Private Subnets

Parameters:
  VPCId:
    Type: String
    Description: VPC Id

Resources:
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCId
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: PublicSubnet

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCId
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: PrivateSubnet

Outputs:
  PublicSubnetId:
    Description: The Public Subnet Id
    Value: !Ref PublicSubnet

  PrivateSubnetId:
    Description: The Private Subnet Id
    Value: !Ref PrivateSubnet
